# Generated by Django 5.0.7 on 2024-07-28 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todos',
            old_name='titile',
            new_name='title',
        ),
    ]
